version: '3'

services:
  pgadmin4:
    image: dpage/pgadmin4:2021-09-06-2
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - PGADMIN_DEFAULT_EMAIL=dxdy@bk.ru
      - PGADMIN_DEFAULT_PASSWORD=postgres
    volumes:
       - pgadmin4:/var/lib/pgadmin
    ports:
      - 5050:80
    restart: always
    networks:
      - postgres

volumes:
  pgadmin4:
    external: true

networks:
  postgres:
      external: true
