version: '3'

services:
  postgis:
    image: postgis/postgis:9.6-2.5
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
    restart: always
    networks:
      - postgres

networks:
  postgres:
    external: true
