
fire:
	docker-compose run --rm yandex-tank yandex-tank -c /var/loadtest/load.yaml

bash:
	docker-compose run --rm yandex-tank /bin/bash

clean:
	sudo rm -rf ./loadtest/logs/*
	sudo rm -rf ./loadtest/*.log
